version: "3.3"

services:
  api:
    build:
      context: .
    image: devstudio-sample-project-api
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    depends_on:
      - redis
      - rabbitmq
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=3000"
    networks:
      - internal

  greeter:
    build:
      context: .
    image: devstudio-sample-project-greeter
    env_file: docker-compose.env
    environment:
      SERVICES: greeter
    depends_on:
      - redis
      - rabbitmq
    networks:
      - internal

  products:
    build:
      context: .
    image: devstudio-sample-project-products
    env_file: docker-compose.env
    environment:
      SERVICES: products
    depends_on:
      - mongo
      - redis
      - rabbitmq
    networks:
      - internal
        
  warehouse:
    build:
      context: .
    image: devstudio-sample-project-warehouse
    env_file: docker-compose.env
    environment:
      SERVICES: warehouse
    depends_on:
      - mongo
      - redis
      - rabbitmq
      - products
    networks:
      - internal

  mongo:
    image: mongo:4
    volumes:
      - data:/data/db
    networks:
      - internal

  redis:
    image: redis:alpine
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:3
    networks:
      - internal

  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - 3000:80
      - 3001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default

networks:
  internal:

volumes:
  data:
